# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Manual.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QIcon


class Ui_ManualWindow(object):
    def setupUi(self, ManualWindow):
        ManualWindow.setObjectName("ManualWindow")
        ManualWindow.resize(1920, 1000)
        self.centralwidget = QtWidgets.QWidget(ManualWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.auto_button = QtWidgets.QPushButton(self.centralwidget)
        self.auto_button.setGeometry(QtCore.QRect(1700, 875, 200, 100))
        self.auto_button.setObjectName("auto_button")
        self.stitch_button = QtWidgets.QPushButton(self.centralwidget)
        self.stitch_button.setGeometry(QtCore.QRect(1700, 550, 200, 100))
        self.stitch_button.setObjectName("stitch_button")
        self.stereo_button = QtWidgets.QPushButton(self.centralwidget)
        self.stereo_button.setGeometry(QtCore.QRect(1700, 700, 200, 100))
        self.stereo_button.setObjectName("stereo_button")
        self.screenshot_button = QtWidgets.QPushButton(self.centralwidget)
        self.screenshot_button.setGeometry(QtCore.QRect(900, 890, 100, 100))
        self.screenshot_button.setObjectName("screenshot_button")
        self.backward_button = QtWidgets.QPushButton(self.centralwidget)
        self.backward_button.setGeometry(QtCore.QRect(875, 800, 150, 75))
        self.backward_button.setText("")
        self.backward_button.setObjectName("backward_button")
        self.forward_button = QtWidgets.QPushButton(self.centralwidget)
        self.forward_button.setGeometry(QtCore.QRect(875, 525, 150, 75))
        self.forward_button.setText("")
        self.forward_button.setObjectName("forward_button")
        self.left_button = QtWidgets.QPushButton(self.centralwidget)
        self.left_button.setEnabled(True)
        self.left_button.setGeometry(QtCore.QRect(750, 625, 75, 150))
        self.left_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.left_button.setText("")
        self.left_button.setObjectName("left_button")
        self.right_button = QtWidgets.QPushButton(self.centralwidget)
        self.right_button.setGeometry(QtCore.QRect(1050, 625, 75, 150))
        self.right_button.setText("")
        self.right_button.setObjectName("right_button")
        self.motion = QtWidgets.QLabel(self.centralwidget)
        self.motion.setGeometry(QtCore.QRect(80, 550, 150, 80))
        self.motion.setAlignment(QtCore.Qt.AlignCenter)
        self.motion.setObjectName("motion")
        self.speed = QtWidgets.QLabel(self.centralwidget)
        self.speed.setGeometry(QtCore.QRect(80, 665, 150, 80))
        self.speed.setAlignment(QtCore.Qt.AlignCenter)
        self.speed.setObjectName("speed")
        self.voltage = QtWidgets.QLabel(self.centralwidget)
        self.voltage.setGeometry(QtCore.QRect(80, 780, 150, 80))
        self.voltage.setAlignment(QtCore.Qt.AlignCenter)
        self.voltage.setObjectName("voltage")
        self.current = QtWidgets.QLabel(self.centralwidget)
        self.current.setGeometry(QtCore.QRect(80, 890, 150, 80))
        self.current.setAlignment(QtCore.Qt.AlignCenter)
        self.current.setObjectName("current")
        self.camera = QtWidgets.QLabel(self.centralwidget)
        self.camera.setGeometry(QtCore.QRect(0, 0, 1920, 500))
        self.camera.setAlignment(QtCore.Qt.AlignCenter)
        self.camera.setObjectName("camera")
        self.motion_pic = QtWidgets.QLabel(self.centralwidget)
        self.motion_pic.setGeometry(QtCore.QRect(0, 550, 80, 80))
        self.motion_pic.setText("")
        self.motion_pic.setAlignment(QtCore.Qt.AlignCenter)
        self.motion_pic.setObjectName("motion_pic")
        self.compasspic = QPixmap('Compass.jpg')
        self.motion_pic.setPixmap(self.compasspic)
        self.speed_pic = QtWidgets.QLabel(self.centralwidget)
        self.speed_pic.setGeometry(QtCore.QRect(0, 665, 80, 80))
        self.speed_pic.setText("")
        self.speed_pic.setAlignment(QtCore.Qt.AlignCenter)
        self.speed_pic.setObjectName("speed_pic")
        self.speedpic = QPixmap('Speed.jpg')
        self.speed_pic.setPixmap(self.speedpic)
        self.volt_pic = QtWidgets.QLabel(self.centralwidget)
        self.volt_pic.setGeometry(QtCore.QRect(0, 780, 80, 80))
        self.volt_pic.setText("")
        self.volt_pic.setAlignment(QtCore.Qt.AlignCenter)
        self.volt_pic.setObjectName("volt_pic")
        self.voltpic = QPixmap('Voltage.jpg')
        self.volt_pic.setPixmap(self.voltpic)
        self.current_pic = QtWidgets.QLabel(self.centralwidget)
        self.current_pic.setGeometry(QtCore.QRect(0, 890, 80, 80))
        self.current_pic.setText("")
        self.current_pic.setAlignment(QtCore.Qt.AlignCenter)
        self.current_pic.setObjectName("current_pic")
        self.currentpic = QPixmap('Current.jpg')
        self.current_pic.setPixmap(self.currentpic)
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(1250, 650, 280, 280))
        self.logo.setText("")
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.logopic = QPixmap('Aquaphoton.jpg')
        self.logo.setPixmap(self.logopic)
        self.caption = QtWidgets.QLabel(self.centralwidget)
        self.caption.setGeometry(QtCore.QRect(350, 650, 300, 300))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.caption.setFont(font)
        self.caption.setAlignment(QtCore.Qt.AlignCenter)
        self.caption.setObjectName("caption")
        self.LF = QtWidgets.QPushButton(self.centralwidget)
        self.LF.setGeometry(QtCore.QRect(750, 525, 75, 75))
        self.LF.setText("")
        self.LF.setObjectName("LF")
        self.RF = QtWidgets.QPushButton(self.centralwidget)
        self.RF.setGeometry(QtCore.QRect(1050, 525, 75, 75))
        self.RF.setText("")
        self.RF.setObjectName("RF")
        self.LB = QtWidgets.QPushButton(self.centralwidget)
        self.LB.setGeometry(QtCore.QRect(750, 800, 75, 75))
        self.LB.setText("")
        self.LB.setObjectName("LB")
        self.RB = QtWidgets.QPushButton(self.centralwidget)
        self.RB.setGeometry(QtCore.QRect(1050, 800, 75, 75))
        self.RB.setText("")
        self.RB.setObjectName("RB")
        self.Drive = QtWidgets.QPushButton(self.centralwidget)
        self.Drive.setGeometry(QtCore.QRect(450, 525, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Drive.setFont(font)
        self.Drive.setObjectName("Drive")
        self.Park = QtWidgets.QPushButton(self.centralwidget)
        self.Park.setGeometry(QtCore.QRect(1350, 525, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Park.setFont(font)
        self.Park.setObjectName("Park")
        ManualWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ManualWindow)
        QtCore.QMetaObject.connectSlotsByName(ManualWindow)

    def retranslateUi(self, ManualWindow):
        _translate = QtCore.QCoreApplication.translate
        ManualWindow.setWindowTitle(_translate("ManualWindow", "MainWindow"))
        ManualWindow.setStyleSheet("background-color: white")
        self.auto_button.setText(_translate("ManualWindow", "Autonomous"))
        self.auto_button.setStyleSheet(
            "QPushButton""{""background-color: #00ffff; border-radius: 30; border: 3px solid""}"
            "QPushButton::Pressed""{""background-color: green""}")
        self.stitch_button.setText(_translate("ManualWindow", "Video Stitching"))
        self.stitch_button.setStyleSheet(
            "QPushButton""{""background-color: #00ffff; border-radius: 30; border: 3px solid""}"
            "QPushButton::Pressed""{""background-color: green""}")
        self.stereo_button.setText(_translate("ManualWindow", "Stereo Vision"))
        self.stereo_button.setStyleSheet(
            "QPushButton""{""background-color: #00ffff; border-radius: 30; border: 3px solid""}"
            "QPushButton::Pressed""{""background-color: green""}")
        self.screenshot_button.setText(_translate("ManualWindow", "Screenshot"))
        self.screenshot_button.setStyleSheet(
            "QPushButton""{""background-color: #00ffff; border-radius: 40; border: 3px solid""}"
            "QPushButton::Pressed""{""background-color: green""}")
        self.motion.setText(_translate("ManualWindow", "Motion"))
        self.motion.setStyleSheet("background-color: white; border: 3px solid black")
        self.speed.setText(_translate("ManualWindow", "Speed"))
        self.speed.setStyleSheet("background-color: white; border: 3px solid black")
        self.voltage.setText(_translate("ManualWindow", "Voltage"))
        self.voltage.setStyleSheet("background-color: white; border: 3px solid black")
        self.current.setText(_translate("ManualWindow", "Current"))
        self.current.setStyleSheet("background-color: white; border: 3px solid black")
        self.camera.setText(_translate("ManualWindow", "Live Feed"))
        self.camera.setStyleSheet("background-color: white; border: 3px solid black")
        self.caption.setText(_translate("ManualWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Training\'24</span></p><p><span style=\" font-weight:600;\">Team 1</span></p></body></html>"))
        self.Drive.setText(_translate("ManualWindow", "Drive"))
        self.Drive.setStyleSheet(
            "QPushButton""{""background-color: #00ffff; border-radius: 50; border: 3px solid""}"
            "QPushButton::Pressed""{""background-color: green""}")
        self.Park.setText(_translate("ManualWindow", "Park"))
        self.Park.setStyleSheet("QPushButton""{""background-color: #00ffff; border-radius: 50; border: 3px solid""}"
                                    "QPushButton::Pressed""{""background-color: green""}")
        self.forward_button.setIcon(QIcon('Forward.png'))
        self.forward_button.setStyleSheet(
            "QPushButton""{""background-color: #00ffff; border-radius: 30; border: 3px solid""}"
            "QPushButton::Pressed""{""background-color: green""}")
        self.backward_button.setIcon(QIcon('Backward.png'))
        self.backward_button.setStyleSheet(
            "QPushButton""{""background-color: #00ffff; border-radius: 30; border: 3px solid""}"
            "QPushButton::Pressed""{""background-color: green""}")
        self.right_button.setIcon(QIcon('Right.png'))
        self.right_button.setStyleSheet(
            "QPushButton""{""background-color: #00ffff; border-radius: 30; border: 3px solid""}"
            "QPushButton::Pressed""{""background-color: green""}")
        self.left_button.setIcon(QIcon('Left.png'))
        self.left_button.setStyleSheet(
            "QPushButton""{""background-color: #00ffff; border-radius: 30; border: 3px solid""}"
            "QPushButton::Pressed""{""background-color: green""}")
        self.RF.setStyleSheet("QPushButton""{""background-color: #00ffff; border-radius: 30; border: 3px solid""}"
                                  "QPushButton::Pressed""{""background-color: green""}")
        self.LF.setStyleSheet("QPushButton""{""background-color: #00ffff; border-radius: 30; border: 3px solid""}"
                                  "QPushButton::Pressed""{""background-color: green""}")
        self.RB.setStyleSheet("QPushButton""{""background-color: #00ffff; border-radius: 30; border: 3px solid""}"
                                  "QPushButton::Pressed""{""background-color: green""}")
        self.LB.setStyleSheet("QPushButton""{""background-color: #00ffff; border-radius: 30; border: 3px solid""}"
                                  "QPushButton::Pressed""{""background-color: green""}")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ManualWindow = QtWidgets.QMainWindow()
    ui = Ui_ManualWindow()
    ui.setupUi(ManualWindow)
    ManualWindow.show()
    sys.exit(app.exec_())
